trigger:
- main

pool:
  name: Default  # Use your agent pool name


steps:
# Pull and push the hello-world image to ACR
- task: Docker@2
  displayName: 'Docker Login'
  inputs:
    command: login
    containerRegistry: 'ACR-Connection'

- script: |
    # Pull the hello-world image
    docker pull hello-world
    
    # Tag and push to ACR
    docker tag hello-world acrrca2344.azurecr.io/hello-world:latest
    docker tag hello-world acrrca2344.azurecr.io/hello-world:$(Build.BuildId)
    
    docker push acrrca2344.azurecr.io/hello-world:latest
    docker push acrrca2344.azurecr.io/hello-world:$(Build.BuildId)
    
    # Save variables for the release pipeline
    echo "##vso[task.setvariable variable=imageTag;isOutput=true]$(Build.BuildId)"
    echo "##vso[task.setvariable variable=buildId;isOutput=true]$(Build.BuildId)"
  displayName: 'Push Hello-World Image to ACR'
  name: PushImage